receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:1111

exporters:
  logging:
    logLevel: debug
  
  otlp/jaeger:
    endpoint: http://jaeger:4318

service:
  pipelines:
    traces/1: 
      receivers: [otlp]
      exporters: [logging, otlp/jaeger]