receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:1111

exporters:
  logging:
    logLevel: debug

service:
  pipelines:
    traces/1: 
      receivers: [otlp]
      exporters: [logging]