version: "3.8"

services:
  jaeger:
    image: jaegertracing/jaeger:2.3.0
    ports:
    - published: 16686
      target: 16686
    - published: 4317
      target: 4317
    - published: 4318
      target: 4318
    environment:
      LOG_LEVEL: debug
    networks:
    - demo

  go-server:
    image: golang:1.21-alpine
    environment:
      GOPATH: /tmp
    working_dir: /app
    networks:
    - demo
    volumes:
    - type: bind
      source: ./src/
      target: /app
    command: go run server.go
  
  go-client:
    image: golang:1.21-alpine
    environment:
      GOPATH: /tmp
    working_dir: /app
    networks:
    - demo
    volumes:
    - type: bind
      source: ./src/
      target: /app
    command: go run client.go
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.40.0
    command:
    - --config
    - /etc/otel/otel-local-config.yaml
    - /otelcontribcol
    ports:
    - target: 1111
      published: 1111
    networks:
    - demo
    volumes:
    - type: bind
      source: ./otel-config/basic-collector-config.yml
      target: /etc/otel/otel-local-config.yaml

networks:
  demo:
