version: "3.8"

services:
  go-server:
    image: golang:1.21-alpine
    name: server
    environment:
      GOPATH: /tmp
    working_dir: /app
    networks:
    - demo
    volumes:
    - type: volume
      source: ./src/
      target: /app
    command: go run server.go
  
  go-client:
    image: golang:1.21-alpine
    name: client
    environment:
      GOPATH: /tmp
    working_dir: /app
    networks:
    - demo
    volumes:
    - type: volume
      source: ./src/
      target: /app
    command: go run client.go
  
  otel-collector:
    name: otelcol
    image: otel/opentelemetry-collector-contrib:0.40.0
    command:
    - --config
    - /etc/otel/otel-local-config.yaml
    - /otelcontribcol
    ports:
    - target: 1111
      published: 1111
    networks:
    - demo
    volumes:
    - type: bind
      source: ./otel-config/instrumentation-collector-config.yml
      target: /etc/otel/otel-local-config.yaml

networks:
  demo:
